import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Modabook",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal } : { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="mx-auto max-w-screen-md px-4 mt-5">{children}</div>
        {modal}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" async></script>
      </body>
    </html>
  );
}
